image: python:3.9


before_script:
    - pip install -r requirements.txt
    - pip install -e .
    - pip show myapp

run tests:
    only:
        - master
    tags:
        - python3
        - tests
    script:
        - cd /workspace
        - python -m pytest
    artifacts:
        name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
        paths:
            - /workspace/coverage/
        when: on_success
        expire_in: 1 week
    coverage: '/TOTAL.*\s+(\d+%)$/'
